### ISSUE TITLE
Makie Roadmap [WIP]

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaPlots/AbstractPlotting.jl#414]
- [ ] colorsampler interface + alpha keyword
- [ ] data space + marker space
- [ ] text + scatter shader rewrite
- [ ] WidgetsBase.jl integration
- [ ] Improve how attributes work https://github.com/JuliaPlots/AbstractPlotting.jl/pull/360
- [ ] Merge MakieLayout
- [ ] Data transforms (log axis etc)
- [ ] Merge most code shared in WGLMakie & GLMakie
- [ ] clean up recipes

**Comment by asinghvi17** [comment]
I wonder if WidgetsBase could be integrated into MakieLayout now? It seems like nearly all of the widgets are, or will soon be supported there.

**Comment by SimonDanisch** [comment]
Yeah we should integrate them in the final version with the MakieLayout widgets!
But I may want to quickly do a first integration with Makie before that, to already figure out the problems with that ;) Makie widgets are much easier, so I assume it will be quite simple to this...
